config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :transactions
  resources :members
  resources :books
  resources :concentrations
  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end
  resources :users
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :author, :concentration_id, :force, :stock, :title
  belongs_to :concentration
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    authorize! :show, @user, :message => 'Not authorized as an administrator.'
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, :label => "Judul" %>
    <%= f.input :author, :label => "Penyusun" %>
    <%= f.input :force, :label => "Tahun Angkatan" %>
    <%= f.input :concentration_id, :collection => Concentration.order(:name), :label_method => :name, :value_method => :id, :label => "Konsentrasi", :include_blank => true %>
    <%= f.input :stock, :label => "Jumlah" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Buat Laporan" if action_name == 'new' %>
    <%= f.button :submit, "Edit Laporan" if action_name == 'edit' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
    <h3>Perbaiki Laporan <small>Tugas Akhir, Laporan Penelitian</small></h3>
</div>
<%= render 'form' %>
<%= link_to 'Kembali', tasks_path, :class => "btn btn-mini" %>

app/views/tasks/index.html.erb
<div class="page-header">
    <h3>Daftar Laporan <small>Tugas Akhir, Laporan Penelitian</small></h3>
</div>

<table class="table table-bordered responsive datatables">
    <thead>  
        <tr>
            <th>Judul</th>
            <th>Penyusun</th>
            <th>Angkatan</th>
            <th>Konsentrasi</th>
            <th>Jumlah</th>
            <% if user_signed_in? %>
              <th></th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
          <tr>
              <td><%= task.title %></td>
              <td><%= task.author %></td>
              <td><%= task.force %></td>
              <td><%= task.concentration.name rescue nil %></td>
              <td><%= task.stock %>&nbsp;Buku</td>
              <% if user_signed_in? %>
                <td><%= link_to 'Tampilkan', task, :class => "btn btn-mini" %>&nbsp;&nbsp;<%= link_to 'Perbaiki', edit_task_path(task), :class => "btn btn-mini" %>&nbsp;&nbsp;<%= link_to 'Hapus', task, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini" %></td>
              <% end %>
          </tr>
        <% end %>
    </tbody>
</table>
<br />
<%= link_to 'Tambah Laporan', new_task_path, :class => "btn btn-mini" if user_signed_in? %>

app/views/tasks/new.html.erb
<div class="page-header">
    <h3>Laporan Baru <small>Tugas Akhir, Laporan Penelitian</small></h3>
</div>
<%= render 'form' %>
<%= link_to 'Kembali', tasks_path, :class => "btn btn-mini" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Author:</b>
  <%= @task.author %>
</p>

<p>
  <b>Force:</b>
  <%= @task.force %>
</p>

<p>
  <b>Concentration:</b>
  <%= @task.concentration_id %>
</p>

<p>
  <b>Stock:</b>
  <%= @task.stock %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>