config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :transactions
  resources :members
  resources :books
  resources :concentrations
  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end
  resources :users
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :judul, :jumlah, :kota_terbit, :pengarang, :tahun_terbit, :location
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    authorize! :show, @user, :message => 'Not authorized as an administrator.'
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    authorize! :edit, @user, :message => 'Not authorized as an administrator.'
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :judul %>
    <%= f.input :pengarang %>
    <%= f.input :tahun_terbit %>
    <%= f.input :kota_terbit %>
    <%= f.input :location %>
    <%= f.input :jumlah %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="page-header">
    <h3>Daftar Buku <small>Koleksi Buku Buku Penunjang</small></h3>
</div>

<table class="table table-bordered responsive datatables">
    <thead> 
        <tr>
            <th>Judul</th>
            <th>Pengarang</th>
            <th>Tahun Terbit</th>
            <th>Kota Terbit</th>
            <th>Jumlah</th>
            <th>Rak Buku</th>
            <% if user_signed_in? %>
              <th></th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
          <tr>
              <td><%= book.judul %></td>
              <td><%= book.pengarang %></td>
              <td><%= book.tahun_terbit %></td>
              <td><%= book.kota_terbit %></td>
              <td><%= book.jumlah %></td>
              <td><%= book.location rescue nil %></td>
              <% if user_signed_in? %>
              <td><%= link_to 'Show', book %>&nbsp;<%= link_to 'Edit', edit_book_path(book) %>&nbsp;<%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
          </tr>
        <% end %>
    </tbody>
</table>

<br />

<%= link_to 'Tambah Buku', new_book_path, :class => "btn btn-mini" if user_signed_in? %>

app/views/books/new.html.erb
<div class="page-header">
    <h3>Buku Baru<small>Koleksi Buku Buku Penunjang</small></h3>
</div>
<%= render 'form' %>
<%= link_to 'Kembali', books_path, :class => "btn btn-mini"  %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Judul:</b>
  <%= @book.judul %>
</p>

<p>
  <b>Pengarang:</b>
  <%= @book.pengarang %>
</p>

<p>
  <b>Tahun terbit:</b>
  <%= @book.tahun_terbit %>
</p>

<p>
  <b>Kota terbit:</b>
  <%= @book.kota_terbit %>
</p>

<p>
  <b>Jumlah:</b>
  <%= @book.jumlah %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>