config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :transactions
  resources :members
  resources :books
  resources :concentrations
  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Sistem Informasi Perpustakaan", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Tugas Akhir', tasks_path %>
    <%#= link_to 'Login', new_user_session_path %>
    </li>
    <li>
    <%= link_to 'Koleksi Buku', books_path %>
    <%#= link_to 'Login', new_user_session_path %>
    </li>
    <li>
    <%= link_to 'Daftar Anggota', members_path %>
    <%#= link_to 'Login', new_user_session_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Tugas Akhir', tasks_path %>
    <%#= link_to 'Login', new_user_session_path %>
    </li>
    <li>
    <%= link_to 'Koleksi Buku', books_path %>
    <%#= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Profile', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Daftar User', users_path %>
      </li>
    <% end %>
    <li>
      <%= link_to 'Keluar', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%#= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sistem Informasi Perpustakaan" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>