config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :transactions
  resources :members
  resources :books
  resources :concentrations
  resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end
  resources :users
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :berlaku, :concentration_id, :kelas, :nama, :email, :nim, :user_id
  belongs_to :concentration
  belongs_to :user
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        user = User.new
        user.email = @member.email
        user.name = @member.nama
        user.password = '12345678'
        user.password_confirmation = '12345678'
        user.add_role(:user)
        user.save
        @member.update_attribute(:user_id, user.id)
        format.html { redirect_to members_url, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])
    user = User.find(@member.user_id)
    user.email = @member.email 
    user.name = @member.nama
    user.save

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to members_url, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    user = User.find(@member.user_id)
    user.destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for(@member) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nim %>
    <%= f.input :nama %>
    <%= f.input :kelas %>
    <%= f.input :email %>
    <%= f.input :concentration_id, :collection => Concentration.order(:name), :label_method => :name, :value_method => :id, :label => "Konsentrasi", :include_blank => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="page-header">
    <h3>Perbaiki Anggota <small>Perbaiki Anggota Peminjam Perpustakaan</small></h3>
</div>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<div class="page-header">
    <h3>Daftar Anggota <small>Daftar Peminjam Perpustakaan</small></h3>
</div>

<table class="table table-bordered responsive datatables">
    <thead> 
        <tr>
            <th>NIM</th>
            <th>Nama Lengkap</th>
            <th>Kelas</th>
            <th>Jurusan</th>
            <% if user_signed_in? %>
            <th></th>
            <% end%>
        </tr>
    </thead>
    <tbody>
        <% @members.each do |member| %>
          <tr>
              <td><%= member.nim %></td>
              <td><%= member.nama %></td>
              <td><%= member.kelas %></td>
              <td><%= member.concentration.name %></td>
              <% if user_signed_in? %>
              <td><%= link_to 'Tampilkan', member %> <%= link_to 'Perbaiki', edit_member_path(member) %> <%= link_to 'Hapus', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
          </tr>
        <% end %>
    </tbody>
</table>
<br />
<%= link_to 'Anggota Baru', new_member_path if user_signed_in? %>

app/views/members/new.html.erb
<div class="page-header">
    <h3>Anggota Baru <small>Anggota Baru Peminjam Perpustakaan</small></h3>
</div>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<div class="page-header">
    <h3>Detail Member</h3>
</div>

<p>
  <b>NIM :</b>
  <%= @member.nim %>
</p>

<p>
  <b>Nama Lengkap :</b>
  <%= @member.user.name %>
</p>

<p>
  <b>Kelas :</b>
  <%= @member.kelas %>
</p>

<p>
  <b>Jurusan :</b>
  <%= @member.concentration.name %>
</p>

<p>
  <b>Masa Berlaku :</b>
  <%= @member.berlaku %>
</p>


<%= link_to 'Perbaiki', edit_member_path(@member) %> |
<%= link_to 'Kembali', members_path %>